/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lugiago.View;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author tiago
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public Menu() {
        initComponents();
        
        // Adicionando iamgem ao menu inicial
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/menu.jpg")).getImage().getScaledInstance(400, 300, Image.SCALE_DEFAULT));
        jLabelImagem.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagem = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMFuncionario = new javax.swing.JMenu();
        jMFuncionarioCadastar = new javax.swing.JMenuItem();
        jMFuncionarioListar = new javax.swing.JMenuItem();
        jMTurno = new javax.swing.JMenu();
        jMTurnoCadastrar = new javax.swing.JMenuItem();
        jMTurnoListar = new javax.swing.JMenuItem();
        jMTurnoAlterar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelImagem.setText("   ");

        jMFuncionario.setText("Funcionário");

        jMFuncionarioCadastar.setText("Cadastrar");
        jMFuncionarioCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFuncionarioCadastarActionPerformed(evt);
            }
        });
        jMFuncionario.add(jMFuncionarioCadastar);

        jMFuncionarioListar.setText("Listar");
        jMFuncionarioListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFuncionarioListarActionPerformed(evt);
            }
        });
        jMFuncionario.add(jMFuncionarioListar);

        jMenuBar.add(jMFuncionario);

        jMTurno.setText("Turnos");

        jMTurnoCadastrar.setText("Cadastrar");
        jMTurnoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTurnoCadastrarActionPerformed(evt);
            }
        });
        jMTurno.add(jMTurnoCadastrar);

        jMTurnoListar.setText("Listar");
        jMTurnoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTurnoListarActionPerformed(evt);
            }
        });
        jMTurno.add(jMTurnoListar);

        jMTurnoAlterar.setText("Alterar");
        jMTurnoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTurnoAlterarActionPerformed(evt);
            }
        });
        jMTurno.add(jMTurnoAlterar);

        jMenuBar.add(jMTurno);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagem)
                .addGap(0, 391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImagem)
                .addGap(0, 264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMTurnoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTurnoListarActionPerformed
        (new TurnoListar()).setVisible(true);
    }//GEN-LAST:event_jMTurnoListarActionPerformed

    private void jMFuncionarioCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFuncionarioCadastarActionPerformed
        (new FuncionarioCadastrar()).setVisible(true);
    }//GEN-LAST:event_jMFuncionarioCadastarActionPerformed

    private void jMFuncionarioListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFuncionarioListarActionPerformed
        (new FuncionarioListar()).setVisible(true);
    }//GEN-LAST:event_jMFuncionarioListarActionPerformed

    private void jMTurnoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTurnoCadastrarActionPerformed
        (new TurnoCadastrar()).setVisible(true);
    }//GEN-LAST:event_jMTurnoCadastrarActionPerformed

    private void jMTurnoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTurnoAlterarActionPerformed
        (new TurnoAlterar()).setVisible(true);
    }//GEN-LAST:event_jMTurnoAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JMenu jMFuncionario;
    private javax.swing.JMenuItem jMFuncionarioCadastar;
    private javax.swing.JMenuItem jMFuncionarioListar;
    private javax.swing.JMenu jMTurno;
    private javax.swing.JMenuItem jMTurnoAlterar;
    private javax.swing.JMenuItem jMTurnoCadastrar;
    private javax.swing.JMenuItem jMTurnoListar;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
